version: "3"
services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_2021
      POSTGRES_DB: root
